[tool.ruff]
target-version = "py311"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true

[tool.djlint]
max_blank_lines = 1
indent = 2
blank_line_after_tag = "load,extends,include"
